/**
 * Content parts that make up a message.
 * Using kebab-case for 'type' to align with AI SDK V3 specifications.
 */

import type { JSONValue, ProviderMetadata } from './types';

/**
 * Tool result output types.
 * Provides structured representation of tool execution results.
 */
export type LanguageToolResultOutput =
  | { type: 'text'; value: string }
  | { type: 'json'; value: JSONValue }
  | { type: 'error-text'; value: string }
  | { type: 'error-json'; value: JSONValue }
  | { type: 'execution-denied'; reason?: string }
  | { type: 'content'; value: LanguageMessagePart[] };

/**
 * Base interface for all content parts.
 */
export interface LanguageContentPartBase {
  /**
   * Additional provider-specific metadata for this content part.
   */
  providerMetadata?: ProviderMetadata;
}

/**
 * Text content part.
 */
export interface LanguageTextContent extends LanguageContentPartBase {
  type: 'text';
  text: string;
  /**
   * Caching configuration for this part.
   */
  cacheControl?: { type?: string };
}

/**
 * File content part (PDF, Audio, Video, Image).
 */
export interface LanguageFileContent extends LanguageContentPartBase {
  type: 'file';
  /**
   * File data. Can be a base64 encoded string, binary data (Uint8Array), or a URL.
   */
  data: string | Uint8Array | URL;
  /**
   * IANA media type of the file (e.g., 'image/png', 'audio/mp3', 'application/pdf').
   */
  mediaType: string;
  /**
   * Optional filename.
   */
  name?: string;
  /**
   * Caching configuration for this part.
   */
  cacheControl?: { type?: string };
}

/**
 * Reasoning or Thinking content part (Chain of Thought).
 */
export interface LanguageReasoningContent extends LanguageContentPartBase {
  type: 'reasoning';
  reasoning: string;
  signature?: string;
}

/**
 * Tool call content part generated by the model.
 */
export interface LanguageToolCallContent extends LanguageContentPartBase {
  type: 'tool-call';
  toolCallId: string;
  toolName: string;
  /**
   * The arguments for the tool call as a JSON object.
   */
  args: JSONValue;
  /** Internal compatibility for OpenAI-style function field */
  function?: {
    name: string;
    arguments: string;
  };
  /**
   * Whether the tool call will be executed by the provider (e.g. MCP, Server-side).
   * If false or undefined, it's executed by the client.
   */
  providerExecuted?: boolean;
  /**
   * Whether the tool is dynamic (defined at runtime).
   */
  dynamic?: boolean;
}

/**
 * Tool result content part provided back to the model.
 */
export interface LanguageToolResultContent extends LanguageContentPartBase {
  type: 'tool-result';
  toolCallId: string;
  toolName: string;
  /**
   * The result of the tool execution.
   * Can be structured output, text, or error information.
   */
  result: LanguageToolResultOutput;
  /**
   * Optional flag if the result is an error or an error message.
   */
  isError?: boolean;
  /**
   * Whether the tool result is preliminary (e.g., an image preview).
   * Preliminary results are replaced by its final version.
   */
  preliminary?: boolean;
  /**
   * Whether the tool is dynamic (defined at runtime).
   */
  dynamic?: boolean;
}

/**
 * Tool approval request emitted by a provider for a provider-executed tool call.
 */
export interface LanguageToolApprovalRequestContent extends LanguageContentPartBase {
  type: 'tool-approval-request';
  /**
   * ID of the approval request.
   */
  approvalId: string;
  /**
   * The tool call ID that this approval request is for.
   */
  toolCallId: string;
}

/**
 * Tool approval response content part containing the user's decision.
 */
export interface LanguageToolApprovalResponseContent extends LanguageContentPartBase {
  type: 'tool-approval-response';
  /**
   * ID of the approval request that this response refers to.
   */
  approvalId: string;
  /**
   * Whether the approval was granted (true) or denied (false).
   */
  approved: boolean;
  /**
   * Optional reason for approval or denial.
   */
  reason?: string;
}

/**
 * Source or citation content part.
 */
export interface LanguageSourceContent extends LanguageContentPartBase {
  type: 'source';
  sourceId: string;
  sourceName?: string;
  uri?: string;
  title?: string;
  text?: string;
}

/**
 * Union type representing any possible part of a language message.
 */
export type LanguageMessagePart =
  | LanguageTextContent
  | LanguageFileContent
  | LanguageReasoningContent
  | LanguageToolCallContent
  | LanguageToolResultContent
  | LanguageToolApprovalRequestContent
  | LanguageToolApprovalResponseContent
  | LanguageSourceContent;
