import {
  LanguageMessagePart,
  LanguageTextContent,
  LanguageFileContent,
  LanguageReasoningContent,
  LanguageToolCallContent,
  LanguageToolResultContent,
  LanguageToolApprovalRequestContent,
  LanguageToolApprovalResponseContent,
} from './content';
import { LanguageTokenUsage } from './usage';
import type { ProviderMetadata } from './types';

/**
 * Common metadata shared by all message types.
 */
export interface LanguageMessageBase {
  /** Raw provider-specific metadata. */
  providerMetadata?: ProviderMetadata;
  /** Standardized telemetry and billing metadata. */
  metadata?: {
    startTime?: number;
    endTime?: number;
    tokens?: LanguageTokenUsage;
    cost?: number;
    [key: string]: unknown;
  };
}

/**
 * System message: Defines model behavior.
 */
export interface LanguageSystemMessage extends LanguageMessageBase {
  role: 'system';
  /** System prompts are usually simple text. */
  content: string;
}

/**
 * User message: Input from the human user.
 */
export interface LanguageUserMessage extends LanguageMessageBase {
  role: 'user';
  /**
   * Supports text and files (including images, audio, video) for multimodal input.
   * Aligned with V3 where images are handled as 'file' parts with specific mediaTypes.
   */
  content: string | Array<LanguageTextContent | LanguageFileContent>;
}

/**
 * Assistant message: Model output including text, reasoning, and tool requests.
 */
export interface LanguageAssistantMessage extends LanguageMessageBase {
  role: 'assistant';
  /**
   * In V3 style, this array captures the sequence of reasoning, text,
   * and tool calls in the exact order they were generated.
   */
  content:
    | string
    | Array<
        | LanguageTextContent
        | LanguageFileContent
        | LanguageReasoningContent
        | LanguageToolCallContent
        | LanguageToolApprovalRequestContent
      >;
  /**
   * The refusal message generated by the model (e.g., when safety filters are triggered).
   * Commonly used by OpenAI models.
   */
  refusal?: string;
}

/**
 * Tool message: Output from tool execution, linked to specific tool calls.
 */
export interface LanguageToolMessage extends LanguageMessageBase {
  role: 'tool';
  /**
   * A tool message contains tool results or approval responses.
   */
  content: Array<LanguageToolResultContent | LanguageToolApprovalResponseContent>;
}

/**
 * Discriminated union of all language message types.
 * Ideal for Agent development where content order and part types matter.
 */
export type LanguageMessage =
  | LanguageSystemMessage
  | LanguageUserMessage
  | LanguageAssistantMessage
  | LanguageToolMessage;
