import { LanguageMessage } from './message';
import { FinishReason } from './finish-reason';
import { LanguageTokenUsage } from './usage';
import type { ProviderMetadata } from './types';

/**
 * Language Model Completion Response.
 * Standardized output format for all language model providers.
 */
export interface LanguageResponse {
  /**
   * Unique ID for the completion.
   */
  id: string;

  /**
   * The Unix timestamp (in seconds) of when the completion was created.
   */
  created: number;

  /**
   * The model ID used for generation.
   */
  model: string;

  /**
   * The generated content options (usually contains just one choice).
   */
  choices: Array<{
    /**
     * The index of the choice in the list of choices.
     */
    index: number;
    /**
     * The message generated by the model.
     */
    message: LanguageMessage;
    /**
     * The reason the model stopped generating tokens.
     */
    finishReason: FinishReason;
  }>;

  /**
   * Usage statistics for the completion request.
   */
  usage?: LanguageTokenUsage;

  /**
   * Extra metadata provided by the specific AI model backend.
   */
  providerMetadata?: ProviderMetadata;
}
